repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: detect-aws-credentials
  - id: detect-private-key
  - id: mixed-line-ending
  #- id: no-commit-to-branch
  #  args: [--branch, master]

- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.43.0
  hooks:
    - id: terraform_docs
    - id: terraform_fmt
    - id: terraform_validate
    #- id: terraform_tflint
    #- id: terraform_tfsec
    #- id: checkov
